CREATE  TABLE `board` (
`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
`user_id` BIGINT(20) NOT NULL,
`title` TEXT NOT NULL,
`content` TEXT NOT NULL,
`deleted` BOOLEAN NOT NULL DEFAULT FALSE,
`updated_at` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
`created_at` TIMESTAMP NOT NULL DEFAULT NOW(),
`view_count`  BIGINT(20) UNSIGNED NOT NULL,
PRIMARY KEY (`id`),
FOREIGN KEY (user_id) REFERENCES users (id))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;